### ISSUE TITLE
Create a Target Group Computed Metric for 2xxs/(2xxs + 5xxs)

### ISSUE THREAD

**Issue by TheConnMan** [netuitive-community-packages/netuitive-packages-aws-alb#5]
This is a specialized metric to specifically capture 2xxs vs 5xxs.

**Comment by bspindler** [comment]
I think you should reconsider calling it `HTTP Success Rate`, and exclude the 4xx and 3xx as I suggested originally.  

If not, I might call the metric I want: 
- HTTP Success Rate (Minus 4xx and 3xx)  
or 
- Service Reliability Index

The calculation is :
 - `successful requests / total requests`
 - successful requests is defined as `HTTP_2xx_Count`
 - total requests is defined as `RequestCount - sum(HTTP_4xx_Count HTTP_3xx_Count)`

It is this computation : 
https://github.com/netuitive-community-packages/netuitive-packages-aws-alb/blob/dev/analyticConfigurations/computed_metric-aws.tag.json#L36  

but changing the `*` to a `-` 
`100 - ${aws.applicationelb.httpcode_target_5xx_count}.actual / ${aws.applicationelb.requestcount}.actual`

Let me know your thoughts.

**Comment by Grumblesmith** [comment]
**I do understand the reasons 5xx are the only errors you care about here,** but 4xx and 3xx aren't successes. Granted, they aren't Server Errors, either.

I'd be fine with calling the metric you want `Service Reliability Index` as the least of several evils, as this _is_ the ratio of HTTP Successes to HTTP Successes and Server Errors.

I'm _not_ fine with defining total requests as either:
  - `HTTPCode_Target_2XX_Count + HTTPCode_Target_5XX_Count` 
or 
  - `RequestCount - HTTPCode_Target_3XX_Count - HTTPCode_Target_4XX_Count`. 

There's a perfectly good total requests measure already: `aws.applicationelb.requestcount` We should call the above measure what it is: "HTTP Successes and Server Errors".

The metric in #6 is being defined as `100 * ${aws.applicationelb.httpcode_target_2xx_count}.actual / (${aws.applicationelb.httpcode_target_2xx_count}.actual + ${aws.applicationelb.httpcode_target_5xx_count}.actual)`. 

That's not the same calculation as `100 - ${aws.applicationelb.httpcode_target_5xx_count}.actual / ${aws.applicationelb.requestcount}.actual`. Is this one the calculation you want used here?

**Comment by bspindler** [comment]
@Grumblesmith and I spoke IRL.  In summary: 

Just for this calculation we’re trying to create, the total requests are defined as `RequestCount - sum(4xx, 3xx)`

The full calculation should be `HTTP_2xx_Count / RequestCount - sum(HTTP_4xx_Count HTTP_3xx_Count)`

Few names have been suggested, I’m fine with `Service Reliability Index` if you are.
